version: '3.9'

services:

  postgres:
    image: 'postgres:13'
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      net:

  fuel-monitoring-back:
    image: mp-analitica-back:latest
    build:
      context: .
    restart: on-failure
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      net:


volumes:
  pg-data:
  second-pg-data:
  redis-data:

networks:
  net:
    driver: bridge
